package com.lanou.mirror.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LOGIN".
 */
public class Login {

    private Long id;
    private String token;
    private String uid;

    public Login() {
    }

    public Login(Long id) {
        this.id = id;
    }

    public Login(Long id, String token, String uid) {
        this.id = id;
        this.token = token;
        this.uid = uid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

}
