package com.lanou.mirror.greendaodemo.entity.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.lanou.mirror.greendaodemo.entity.greendao.LabelEntity;

import com.lanou.mirror.greendaodemo.entity.greendao.LabelEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig labelEntityDaoConfig;

    private final LabelEntityDao labelEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        labelEntityDaoConfig = daoConfigMap.get(LabelEntityDao.class).clone();
        labelEntityDaoConfig.initIdentityScope(type);

        labelEntityDao = new LabelEntityDao(labelEntityDaoConfig, this);

        registerDao(LabelEntity.class, labelEntityDao);
    }
    
    public void clear() {
        labelEntityDaoConfig.getIdentityScope().clear();
    }

    public LabelEntityDao getLabelEntityDao() {
        return labelEntityDao;
    }

}
