package com.lanou.mirror.greendaodemo.entity.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LABEL_ENTITY".
 */
public class LabelEntity {

    private Long id;
    private String labelname;

    public LabelEntity() {
    }

    public LabelEntity(Long id) {
        this.id = id;
    }

    public LabelEntity(Long id, String labelname) {
        this.id = id;
        this.labelname = labelname;
    }
    public LabelEntity(String labelname) {

        this.labelname = labelname;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLabelname() {
        return labelname;
    }

    public void setLabelname(String labelname) {
        this.labelname = labelname;
    }

}
