package com.lanou.mirror.greendaodemo.entity.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SPECIAL".
 */
public class Special {

    private Long id;
    private String Story_title;
    private String Story_img;

    public Special() {
    }

    public Special(Long id) {
        this.id = id;
    }

    public Special(Long id, String Story_title, String Story_img) {
        this.id = id;
        this.Story_title = Story_title;
        this.Story_img = Story_img;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getStory_title() {
        return Story_title;
    }

    public void setStory_title(String Story_title) {
        this.Story_title = Story_title;
    }

    public String getStory_img() {
        return Story_img;
    }

    public void setStory_img(String Story_img) {
        this.Story_img = Story_img;
    }

}
